# Generated by Django 3.0.10 on 2020-09-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20200919_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='author',
            field=models.CharField(default='Anonim', max_length=255),
        ),
    ]
